
# docker-compose.yml

networks:
  microservices-net:
    name: microservices-net
    driver: bridge

services:
  product-service:
    build:
      context: .
      dockerfile: services/product-service/Dockerfile
    ports:
      - "8081:8080"
      - "9091:9091"
    environment:
      - ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=products
      - DB_SSLMODE=disable
      - MIGRATIONS_PATH=services/product-service/internal/migrations
      - SERVER_PORT=8080
      - SERVER_TIMEOUT=30
      - LOG_LEVEL=info
      - SERVICE_NAME=product-service
      - SERVICE_VERSION=1.0.0
      - TELEMETRY_ENABLED=true
      - TELEMETRY_OTLP_ENDPOINT=jaeger:4317
      - TELEMETRY_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - TELEMETRY_METRICS_ENABLED=true
      - TELEMETRY_METRICS_PORT=9091
      - TELEMETRY_PROMETHEUS_PATH=/metrics
    depends_on:
      - postgres
    networks:
      - microservices-net

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=products
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-net

volumes:
  postgres_data:
