api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":8888"
  traefik:
    address: ":8080"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "microservices-net"

log:
  level: "DEBUG"

accessLog: {}

metrics:
  prometheus: {}

# Enable tracing with Jaeger
tracing:
  serviceName: "traefik"
  jaeger:
    collector:
      endpoint: "http://learn-microservice-jaeger-1:14268/api/traces"
    samplingType: "const"
    samplingParam: 1.0
    propagation: "jaeger"
    traceContextHeaderName: "uber-trace-id"
